### ISSUE TITLE
fitting/onlining modules pops bogus error messages based on values BEFORE skills are taken into account

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#10]
**Describe the bug**
When onlining a module in ship fitting, you will receive error popups that are based on the ship's *base* CPU and powergrid (not taking skills into account).   The module will still come online as long as the *actual* need is met.

**To Reproduce**
Train Electronics 5.  Have Fit a ship near it's *base* CPU capacity.   Fit or Online a Large Shield Extender II.  See a bogus error message.

![Example](https://user-images.githubusercontent.com/51723245/59391059-bc660b80-8d38-11e9-9052-6fd769f8a000.PNG)

**Comment by zhyrohaad** [comment]
wow, thats a new one.
modules (ex. caps) were 95% complete at one time.
this will be high priority

**Comment by zhyrohaad** [comment]
this looks to be a data processing error.
as i am reviewing module code, i'll look into this more also.

**Comment by zhyrohaad** [comment]
this may have some deeper problems than i am currently aware of.
ive gotten some weird errors when testing this on the updated main server.
however, pls test again and let me know of your findings.

**Comment by ryllae** [comment]
Bug still present.  The easiest way to make this bug appear is to fit something would otherwise NOT fit without skill training.  e.g. a 10MN Afterburner I on a Hawk.  It only has 45MW by default, but with Engineering 5, you have 56.3 > the 50 you need.  But you get a warning that you only have 45 of 45 available.

**Comment by zhyrohaad** [comment]
this is part of the effects system bug, and appears to be fixed.
i will post again when i update main

**Comment by zhyrohaad** [comment]
main is updated and this appears to be fixed......kinda.

why kinda?
the values im getting in space arent exactly matching up with whats showing while docked.
for those that dont know, fit window values are calculated on client side when docked, and requested from server when in space.
they *should* match, and most times they do, but now they not, and im not sure why.
it's a bit higher in space, and im tired of searching.   all the math im using is right, it all checks out, but it still differs from client.

i digress.
test again now that main is updated, pls.

**Comment by ryllae** [comment]
I'm not getting the error, so I'll consider this closed.  I'll take a look at the math later this weekend and see if I see the same discrepancies or any patterns.

**Comment by ryllae** [comment]
Nope, found a way to pop this bug again.  You get a bogus error when fitting a Cap Power Relay II to a Rhea: when fully trained, it should *just barely* fit, consuming 6 of my 6.3 CPU.  The error message still says I need 8.
![Capture32](https://user-images.githubusercontent.com/51723245/63744404-e376a880-c864-11e9-8dd1-4e950572cfce.PNG)

**Comment by zhyrohaad** [comment]
any errors in fitting window while docked cannot be changed or modified by server, so this isnt something i can 'fix'
