### ISSUE TITLE
Cannot attack wrecks

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#100]
Wrecks should be explodable.  I currently get a serverref error when attepting to shoot one.

**Comment by zhyrohaad** [comment]
at this time, that behavior is correct.
when weapons/targets were written, moving items was still iffy, so if the wreck has any loot, that loot would be lost.
then there's the whole point of "when ya kill a wreck, does it leave a wreck?"

so, the easiest and quickest option was to completely deny attacking wrecks.
also, because they are considered 'space containers', garbage collection will remove them 2h after creation, so the "kill to remove" is a fairly moot point.
other than that, i see no real reason to kill wrecks, so without argument otherwise, they will remain invalid targets.....but is open to discussion.

**Comment by ryllae** [comment]
You can deny loot to people by blowing up their wrecks.  That's all.

**Comment by zhyrohaad** [comment]
ohhh  griefing.
that is a prefect argument.
will update code tonite.

**Comment by ryllae** [comment]
That's not supposed to inspire enthusiasm.

If I recall correctly, popping someone else's can or wreck gives a suspect flag, just like stealing it?

**Comment by zhyrohaad** [comment]
LOL.  point taken.  ;)

you are recalling correctly.
too bad the aggression code isnt written yet.

**Comment by zhyrohaad** [comment]
done and updated.
however, this may fit into #108 so a good test would be have multiple modules on a target that gets destroyed/removed.
all modules run the same basic process for removal/deletion of target (as required), but slightly different.

**Comment by ryllae** [comment]
I can target the wrecks, but my 2000dps Vindictor can barely hit the wreck for 20 dmg, and that dmg doesn't seem to go anywhere (the structure never budges)

**Comment by zhyrohaad** [comment]
Ok.  Will look into this later.

**Comment by zhyrohaad** [comment]
there is missing data somewhere for wreck damage.
i get multiple errors when attacking wrecks that i cannot solve, because i dont know what client expects.  (no appropriate packet data for this client version)
because of this, wrecks will remain invulnerable.

**Comment by ryllae** [comment]
When you consciously decide how software should work, it helps to update the design documents accordingly.   I suggest tagging this issue as "Will Not Fix", and also writing this down somewhere in a concise list of "the things that we're willfully deviating from".  Maybe use github wiki or the code status page?    Also recommend putting a `// @see: https://github.com/zhyrohaad/AlasiyaEvE/issues/100` in the code above whatever is implementing (or not implementing as the case may be), just as a cross reference.  It's avoid "_oh, THAT's what we did_" moments.

Do something along those lines, then we can close this?

**Comment by zhyrohaad** [comment]
i have extensive notes on dev server about the "whys and whats" concerning some of the eccentric code, as well as multiple comments in the codebase concerning oddball things, whether it's design limitations, lack of understanding, not smart enough to implement, or any combination of these.
also, i had started posts on my forums about how, when, why, and where i deviate from live.
these posts also touch on descriptions, design, logic, expected use, and other information on the different systems in the alasiya evemu code.
right now posting to my forums is broken, and i havent had time to fix.

however, you have a good suggestion....i didnt think about the "wont fix" flag on here.
