### ISSUE TITLE
Taking armor damage fully repairs your structure

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#106]
Get a Armageddon Navy Issue into 75% structure damage.  Activate _one_ cycle of a large armor repair module.  Any further damage taken to armor fully repairs your structure.

**Comment by zhyrohaad** [comment]
whoa.
that's an interesting find.
will test/track this one tonite

**Comment by zhyrohaad** [comment]
finally found it.
this was a good one.
the "bleedthru" damage from armor uniformity wasnt taking current hull damage into account, thereby resetting hull damage to the "new" bleedthru value.
still testing fix, so havent updated main yet.

**Comment by zhyrohaad** [comment]
fixed, tested, updated

**Comment by ryllae** [comment]
Yea!  That was a fun bug.
