### ISSUE TITLE
Damage is not saved upon docking

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#107]
Upon docking a ship in hull or structure dmg, or with modules damaged, you should have to use a Repair Service at the station to fix this.  Instead, you get a free repair everytime you dock up.

**Comment by zhyrohaad** [comment]
this is currently a feature using a config switch.
while server is classified as "debugging", undocking will repair ship fully.
this was coded/implemented before i got repair service working, and havent disabled it yet.

**Comment by zhyrohaad** [comment]
With repair service mostly working, the "repair ship on undock" call has been removed.

**Comment by ryllae** [comment]
I don't see this working yet, but I'll keep trying.

**Comment by zhyrohaad** [comment]
touch

**Comment by ryllae** [comment]
Confirmed on dev `eb777b`: all damage is removed after docking up.

**Comment by zhyrohaad** [comment]
found it.
as part of the fx system, attributes are reset when docking.
this includes all damage attributes.

this has been corrected.

**Comment by ryllae** [comment]
Working.
