### ISSUE TITLE
Strip Fitting "offlines" Modules without removing them

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#11]

**Comment by zhyrohaad** [comment]
strip fitting, and save fitting too, are not implemented yet.
these systems have no code at this time.

**Comment by ryllae** [comment]
Although it "offlines" the modules, it's unclear what their real state is.

**Comment by zhyrohaad** [comment]
i missed this bug, so this report is delayed.
`StripFitting()` is finished and working as intended.
main server is updated.

**Comment by ryllae** [comment]
Works as intended!  As long as you don't have a phantom slot...
