### ISSUE TITLE
Destroy Active Probes causes a segfault

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#110]
Launch a Sisters Core Scanner Probe.  Open the scanner window, click "Destroy Active Probes".  SEGFAULT.

**Comment by zhyrohaad** [comment]
incomplete code.
i KNEW i was forgetting something.

**Comment by zhyrohaad** [comment]
delete is fixed.
had to write a specific Delete() method for probes.
still working on remainder of probe/scan code.
eta unknown at this time.

** edit  12aug20 **
most of probe/scan code has been completed.
have not tested very much, except for highlights and proper operation under controlled conditions
actual scan probe signal strength formulas will need some tweaking after a bit more testing, but are working for now.

**Comment by ryllae** [comment]
doesn't crash, good enough for now
