### ISSUE TITLE
System scanner window doesn't update 

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#112]
Open the system scanner window, then launch probes.  THey don't appear until you close then reopen the window.   

ALso, click recover probes.  The window shows them being recovered, they enter your inventory, but stay stuck on the screen.  CLosing and reopening the scanner window may cause a segfault?

**Comment by zhyrohaad** [comment]
scan system is still WIP.
while there are some parts of it considered "fully functional", the system as a whole has other parts that are barely skeleton code, or just placeholders with notes on how to implement.
the refresh is one of the latter.

**Comment by zhyrohaad** [comment]
have most of this system working now.
still few bugs and mildly incomplete.
main not updated yet.

** edit 12aug20 **
main updated

**Comment by ryllae** [comment]
doens't seem to crash, I'll call it good enough until it doesn't work right later

**Comment by zhyrohaad** [comment]
lol
fair enough
