### ISSUE TITLE
Tractor beam doesn't disengage when target disappears

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#114]
Engage a tractor beam on a wreck, salvage it.  the tractor beam continues to cycle after the wreck is gone.  Likewise for a cargo container, after you hit "loot all"

**Comment by ryllae** [comment]
This is in contrast to https://github.com/zhyrohaad/AlasiyaEvE/issues/101, which causes a segfault.

**Comment by zhyrohaad** [comment]
This is something I noticed in my latest testing....I ran a salvager on a wreck along with every other module I could activate on it, for a total of 5, and sometimes it would segfault, sometimes cycle forever, and sometimes would deactivate properly.
This obviously is sorely incomplete.

**Comment by zhyrohaad** [comment]
with latest rounds of targetMgr updates, i can no longer duplicate this error.
will push updates to main tonite (2mar20)

**Comment by ryllae** [comment]
Looks good.  Salvagers still crash though.
