### ISSUE TITLE
Can't find rats

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#115]
I sat in belts in both 1.0 and -0.9 space for about an hour, didn't see any rats.

**Comment by zhyrohaad** [comment]
Mmmmmm.....they **may** be "turned off" in very high sec, 0.9+.

*Edit*
Am I seeing that right?  One belt was in null sec?   -0.9?

**Comment by ryllae** [comment]
Yes, I was over in Period Basis, 08S-39 or thereabouts.

**Comment by zhyrohaad** [comment]
I've heard that before on main server, but no clue why.
On dev server, which uses same code and same config settings, belt rats warp in within 30s of me entering a belt.
This will be looked at soon

**Comment by ryllae** [comment]
found some rats in -0.9 space, they appeared almost immediately.  They weren't very threatening?

**Comment by zhyrohaad** [comment]
rats scale with system security.
there was a post on forums with general spawn groups and how i have Systems grouped.
will look for it when i get time.
