### ISSUE TITLE
Fix the autopilot 

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#117]
I know it's never worked since I've been here, but it would be really nice to be able to warp to a station and auto-dock.  qualityOfLife++;

**Comment by zhyrohaad** [comment]
I've messed with the AP on-n-off for last 6 years.  We're not any closer than we were when I started.

Well, that's not entirely accurate...I have gotten it to work sporatically, but not more than 8 jumps, which is rare.  However, I do know a few things about that system now, but not enough to debug further.

**Comment by zhyrohaad** [comment]
at this point, im gonna call this one "Wont Fix" just because of the lack of data needed to debug the AP system (on client side)
if things change, this can be revisited at a later date.
