### ISSUE TITLE
Repair Service segfault

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#119]
When I dock up, open the repair service, select all items, click Repair, I get a segfault.  Something in my inventory can't be repaired?

**Comment by zhyrohaad** [comment]
touch

**Comment by ryllae** [comment]
Confirmed on dev `eb777b`:  Give yourself a pile of crap (or 50 of everything), click repairshop, select all, repair, crash.

**Comment by zhyrohaad** [comment]
I have not been able to `select all` in repair window.  How are you doing this?

**Comment by ryllae** [comment]
Try "ctrl-a"

**Comment by zhyrohaad** [comment]
found and fixed
main server updated

**Comment by ryllae** [comment]
I clicked, repairshop, ctrl-a, repair item, crash.

**Comment by zhyrohaad** [comment]
i cant reproduce this error

**Comment by ryllae** [comment]
better now.
