### ISSUE TITLE
Undocking with a broken weapons group segfaults

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#121]
Undock an ANI, and group your 7 energy turrets  Dock up.  Remove a weapon.  You get a message saying you will break your weapon group.  Ok.  Remove another weapon (get another error message, but why?  We should have broken the weapon group?)  Keep doing this until you've removed all 7.

Now equip 7 new (different) turrets.  Undock, crash.

**Comment by ryllae** [comment]
Part of https://github.com/zhyrohaad/AlasiyaEvE/issues/82

**Comment by zhyrohaad** [comment]
touch

**Comment by ryllae** [comment]
Confirmed on dev `eb777b`, exactly as above.  You can even do this with 2 blaster cannons on any ship.

**Comment by ryllae** [comment]
Upon logging back in, I get a `There was an error loading a weapon group master.  ServerError 06123`

**Comment by zhyrohaad** [comment]
ohhhh  that's helpful.
i havent actually looked at this yet, but that error msg/# tell me where the problem is.
i need to finish that error system for everything else.  :)

**Comment by zhyrohaad** [comment]
Updated.
The weapon grouping code was missing a call to delete the group data when client requested a module removed from the group.
This has been fixed and main updated.

**Comment by ryllae** [comment]
I recreated an 8-blaster group, docked up, removed one blaster (got the error message saying I was breaking a group), undocked, crashed.  Only other thing that seemed out of order was the the weapon I removed had no charges (which is obviously a different bug).

**Comment by zhyrohaad** [comment]
with current updates, i havent been able to segfault from grouping weapons
not gonna say fixed, as there are still problems with grouping, but i dont see a way to fix using client code.
see what you get when you get a min, then continue on the other weapon group errors. #82

**Comment by ryllae** [comment]
No longer crashes, but there's a laundry list of group ammo problem.

**Comment by zhyrohaad** [comment]
yeah, this is more complicated than i had originally thought.  
theres still a bit of work to do on it.
