### ISSUE TITLE
Can activate multiple tractor beams, can't deactivate them, crashes

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#123]
As in https://github.com/zhyrohaad/AlasiyaEvE/issues/56, activating a 2nd tractor beam gives the error `no messageId 259628`, but the tractor beam module engages anyway.  You cannot deactivate it.  If the wreck disappears (say, you finished salvaging), the server segfaults after a couple more cycles?

**Comment by ryllae** [comment]
The crash could also be from the salvagers that I was using: https://github.com/zhyrohaad/AlasiyaEvE/issues/101

**Comment by zhyrohaad** [comment]
touch

**Comment by ryllae** [comment]
Confirmed on dev `eb777b`.  Equip a Noctis with 4 tractor beams, put them all one one wreck, you can't turn them off.  They keep spinning even after the wreck is gone.

**Comment by zhyrohaad** [comment]
This is a module process error for tractors, and may affect other modules, specifically salvagers.  Have also found the tractor object doesn't move on players screen.
I am currently  working it,  with no ETA.

**Comment by zhyrohaad** [comment]
fixed and updated

**Comment by ryllae** [comment]
can no longer have multiple tractor beams.  But a successful salvager still either crashes other salvagers or the tractor beam.
