### ISSUE TITLE
Jumping through a gate doesn't notify other players in the incoming bubble

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#125]
Undock two ships, head to the nearest gate.  Have ship B jump through, then jump back.   B can see A, but A can't see B.   B can even target A and activate hostile modules, but A won't even see the yellowbox or target back.

**Comment by zhyrohaad** [comment]
touch

**Comment by ryllae** [comment]
Tested on dev `eb777b`:  Even worse, when B jumped and jumped back, she was in a DIFFERENT(/new) bubble than A.  I then had A jump and come back, which joined B in the NEW bubble: A could see B, but B couldn't see A.

**Comment by zhyrohaad** [comment]
this was an error with setting the solar system data for the ship before jumping (it wasnt)
it is fixed and main updated

**Comment by ryllae** [comment]
Working, in fact I think players are getting OVER-notified.  I'm going to reopen https://github.com/zhyrohaad/AlasiyaEvE/issues/127
