### ISSUE TITLE
Targeting a structure crashes

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#130]
Tested on dev `eb777b`: 

Ctrl-Left click in the overview on a station or gate to start targeting.  CRASH.

This was previously forbidden, and worked correctly.

**Comment by zhyrohaad** [comment]
while reworking target manager, i also revamped when and how checks were made.
seems i didnt do a very good job of verifying the code before pushing it.
this has been fixed.

**Comment by ryllae** [comment]
Fixed.
