### ISSUE TITLE
Reppers and passive shield repair don't update other clients 

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#136]
Lock an ANI, shoot it into structure damage, activate armor, hull reps.  Wait for your shields to repair.  The aggressor never sees the healing until he applies new dmg.

**Comment by zhyrohaad** [comment]
im guessing this is your own reppers, and not rr?
im not sure where the call for repair is done, but seems like the notification isnt being sent out to all interested parties.
should be an easy fix.

**Comment by zhyrohaad** [comment]
was easy fix.
added call to update interested parties when ship repairs

**Comment by ryllae** [comment]
Looks good.
