### ISSUE TITLE
training que not working as acpected

### ISSUE THREAD

**Issue by Anora** [zhyrohaad/AlasiyaEvE#138]
**Describe the bug**
when attempting to train more then 1 skill the ques will empty it self and no longer work or work partially for a bit and then leave a skill whit 3 seconds left to finish but never complete

**To Reproduce**
Steps to reproduce the behavior: try to que up more then 1 skill to train

**Expected behavior**
que stais active and correctly trains all skill

I'm currently stuck whit a skill i cannot finish training

**Comment by zhyrohaad** [comment]
i dont know of a workaround for this.
i am currently looking into skill training code and will update when i get done.
current eta is unknown.

**Comment by zhyrohaad** [comment]
skill code has been completely rewritten.
all tests have passed, and i havent found any problems with it.
please test again and report.

**Comment by Anora** [comment]
Skill seam to train as normal but que will not persist if you leave for s small period of time and will go back to not training but what was learned before logging off stais other than that trains fine unless you have something that will take a long time to train

**Comment by zhyrohaad** [comment]
i cannot reproduce this

**Comment by Anora** [comment]
all working now

**Comment by Anora** [comment]
ok training is working but if you log off for more 5 minute the skill/ skill que in training will drop and basically progress stops, and the last skill training will be labeled as skill is nearly done training when its not
