### ISSUE TITLE
Strip Miners don't harvest any ore

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#139]
Equip a hulk with ORE Strip Miners.  target a rock, begin shooting.

You don't a percent of the rock if you stop the cycle early.  You get nothing every time it cycles.  

I guess #91 is fixed by virtue of NOTHING happening instead...

**Comment by zhyrohaad** [comment]
while digging into item movement (container inventory errors), i have found a few things that may relate to this.
will post when i know more

**Comment by zhyrohaad** [comment]
this seems to be fixed

main is not updated as of yet.

**Comment by zhyrohaad** [comment]
main server has been updated

**Comment by ryllae** [comment]
I get ore once more!  Though I might have found OTHER problems...
