### ISSUE TITLE
Unable to warp

### ISSUE THREAD

**Issue by Anora** [zhyrohaad/AlasiyaEvE#143]
**Describe the bug**
Ship will not warp to things greater 30AU away

**To Reproduce**
A tempt to warp whit a small frig to a structure/gate/planet/moon greater 30AU

**Expected behavior**
should start warp and warp you to the fathers your cap can take you drop out of warp and attempt to warp again whit what cap you have gained back

**Screenshots**
https://mega.nz/file/qXIHlKrR#HfYgoAcFpFPjfcUdrWE2kAswwyaMIwk94qgMc4CX9lQ

**Comment by zhyrohaad** [comment]
i have not been able to duplicate this.
still working on it.

**Comment by Anora** [comment]
working now
