### ISSUE TITLE
BPO's not being delivered

### ISSUE THREAD

**Issue by Anora** [zhyrohaad/AlasiyaEvE#147]
**Describe the bug**
So i tried to buy some bpo's and they don't get delivered, tried a few different types and nothing

**To Reproduce**
Attempt to perches BPO's isk is taken but nothing delivered to hanger

**Expected behavior**
when perches a BPO is will be taken from your account and the BPO should be delivered to your hanger or the hanger of the station it resides at

**Comment by zhyrohaad** [comment]
was an error in db call where i updated on dev server, but forgot to update main with new data.
this is corrected.

**Comment by Anora** [comment]
confirmed fixed
