### ISSUE TITLE
Failed to record the order in the DB!

### ISSUE THREAD

**Issue by Anora** [zhyrohaad/AlasiyaEvE#148]
**Describe the bug**
Failed to record the order in the DB!
can't place sell orders

**To Reproduce**
attempt to sell something

**Expected behavior**
sell order should work and be recorded to DB

**Screenshots**

**Additional context**
market needs buy orders from NPC, as well as the current seeded stuff dose show up if you go into the detail of that npc sell order

**Comment by zhyrohaad** [comment]
took me a while, but found the error.
i updated market code (was working on rewrite) and didnt update main db.
will work on that tonite

***UPDATE***
this has been fixed
pls test again to verify

**Comment by Anora** [comment]
stil getting the error Failed to record the order in the DB!

**Comment by zhyrohaad** [comment]
omg.
i updated wrong database.  :/
fixing now

**update**
done

***update again***
ive seen more errors on main server regarding market data.
this doesnt seem to be completely fixed as of yet.
will look into more, and post when relevant info becomes available

**Comment by zhyrohaad** [comment]
found and fixed multiple market db errors last nite.
main server updated.
test again and report pls.

**Comment by Anora** [comment]
working 100%
