### ISSUE TITLE
In refewrance to case #138

### ISSUE THREAD

**Issue by Anora** [zhyrohaad/AlasiyaEvE#150]
**Describe the bug**
ok training is working but if you log off for more 5 minute the skill/ skill que in training will drop and basically progress stops, and the last skill training will be labeled as skill is nearly done training when its not

**To Reproduce**
train something  whit more then an our worth of training and leave game for a bit and come back skill is no longer training and que is empty

**Expected behavior**
que and training should persist when player is offline

**Comment by zhyrohaad** [comment]
this is an odd bug
char skill queue isnt loading on char login, and havent found out why.
am looking into it and will update once i figure it out

***update***
character object is not being removed from memory when you log out, so if you log back in and the server hasnt restarted, your character is still in memory, so isnt loaded.
as to why the data is lost when char logs out, i dunno.....still looking into it

**Comment by zhyrohaad** [comment]
found and fixed.
character was not being unloaded properly.
test again to verify pls

**Comment by Anora** [comment]
training working 100%, would like to tackle implants next but more important stuff stuff to do

**Comment by zhyrohaad** [comment]
implants arent coded yet.
not very high on the list, so no point in trying them at this time.
