### ISSUE TITLE
Locking object in warp crashes client/server

### ISSUE THREAD

**Issue by h4h4h4** [zhyrohaad/AlasiyaEvE#16]
**Describe the bug**
locking a object in mid-warp crashes client/server

**To Reproduce**
try to lockup a gate or anything on screen in midwarp.

**Expected behavior**
You cannot lock it while in warp.

**Screenshots**

**Additional context**

**Comment by zhyrohaad** [comment]
whoa.  thats a good one i havent thought about.
should be an easy fix, tho.
thanks

**Comment by zhyrohaad** [comment]
turns out i have thought about this one.
there are checks in target method for warping, among other things.
this processes correctly on dev server, which denies targeting and notifies pilot of some bullshit about disruption of target systems from the warp field.

i dont know what to update at this point for this problem.
will test again when i update main server to verify non-issue.

**Comment by zhyrohaad** [comment]
tested and cannot reproduce.
please test again to verify

**Comment by ryllae** [comment]
I was able to reproduce this one.  Warp to zero toward a gate.  As you approach the gate, keep mashing "lock" on the gate itself.  You'll crash the server right while decelerating back into normal space.

**Comment by ryllae** [comment]
Actually, this has nothing to do with warp.  You just can't lock gates / stations / etc at all without a crash.

https://github.com/zhyrohaad/AlasiyaEvE/issues/59

**Comment by zhyrohaad** [comment]
i still havent looked into this one.

**Comment by zhyrohaad** [comment]
this is a good one.
got segfaults but no luck tracking them yet.
will update when i make headway.

**Comment by zhyrohaad** [comment]
found, fixed, and updated

**Comment by zhyrohaad** [comment]
any update on this?

**Comment by ryllae** [comment]
#59 superseded this bug and was the actual issue - had nothing to do with warping.  Can confirm that was fixed.

Oddly, when targeting a structure, you also see this as an exception in the client (`10094	2020.01.15 02:53:02:560	UserError: [DeniedTargetInvulnerable.notify] None - Target is invulnerable. {}`)?  Not a big deal.

If originator doesn't respond, I'd say close this.

**Comment by zhyrohaad** [comment]
that client error could be from me sending the data incorrectly.
i'll note it and move on.

**Comment by zhyrohaad** [comment]
agreed
