### ISSUE TITLE
unable to mine 

### ISSUE THREAD

**Issue by h4h4h4** [zhyrohaad/AlasiyaEvE#17]
**Describe the bug**
unable to engage asteroid with mining lasers 

**To Reproduce**
warp to belt , lock up asteroid, activate mining mobule ( strip miner I or miner) and wait for message 

**Expected behavior**

**Screenshots**
![2019 07 03 18 43 19](https://user-images.githubusercontent.com/52507060/60617239-3a16b780-9dcb-11e9-9db3-346f41ca38b7.jpg)

**Additional context**

**Comment by zhyrohaad** [comment]
duplicate issue with #2 and #5.
at least this one has proper naming of object.  ;)

**Comment by zhyrohaad** [comment]
mining is working
this fix has been pushed to main server.
please test again to verify the fix
![2019 08 06 06 18 34](https://user-images.githubusercontent.com/6365054/62521351-1ba24280-b7f5-11e9-9172-2fdf7545bd2c.png)

**Comment by ryllae** [comment]
Tested with Strip Miners, I have some Veldspar now.

**Comment by zhyrohaad** [comment]
@h4h4h4 please verify this is fixed so we can close this issue

**Comment by zhyrohaad** [comment]
am closing this one personally as there has been no response by @h4h4h4
