### ISSUE TITLE
Repacking a ship retains its fitting

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#18]
Fit a ship, repackage it, then reassamble it.  You'll find all the modules still on the ship (offlined).

Suspect you need to properly implement https://github.com/zhyrohaad/AlasiyaEvE/issues/11 to make repackaging work as intended.

**Comment by zhyrohaad** [comment]
repacking doesnt use Strip() code.
however, i'm gonna look at it and post back with my findings

**Comment by zhyrohaad** [comment]
repacking updated.
it will now test for fitted modules and items in cargo.

pls test and verify

**Comment by ryllae** [comment]
looks good!
