### ISSUE TITLE
Unfitting a module doesn't free the slot, and crashes the server in several ways

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#19]
Fit 3 Strip Miners to a hulk.  Remove one or more.  If you attempt to re-add them, you get a message saying there is no free slot.

**Comment by ryllae** [comment]
If you have a "phantom empty slot" and hit "Strip Fitting", you get a *server crash*.  Probably related to https://github.com/zhyrohaad/AlasiyaEvE/issues/11 attempting to Offline something that doesn't exist.

**Comment by ryllae** [comment]
Because of https://github.com/zhyrohaad/AlasiyaEvE/issues/18, you can't even repackage the reassemble the ship to get rid of the phantom empty slot.

**Comment by ryllae** [comment]
If you click "Strip Fitting" before you remove any modules, it will offline modules (though I have seen some visual bugs).  You can then remove the modules and re-add them safely.

**Comment by ryllae** [comment]
If you add a module, and remove it (by any means), then log out, it appears to cause a *server crash* (probably trying to persist the invalid ship).   When you relog in, you get a "there is something already in that slot" audio, the login fails.  If you log in a second time, the ship appears to be fine, and you can logout and back in freely.

**Comment by zhyrohaad** [comment]
ive tested this on dev server extensively and have not see anything like this.
will test again and check main for differences, but there shouldnt be any

**Comment by zhyrohaad** [comment]
i was able to reproduce the 'phantom slot' bug.
this has been corrected with the major module code update.
i still dont have `StripFitting` coded, so i should disable it till its working.

**Comment by zhyrohaad** [comment]
turns out after a bit of searching, `StripFitting()` is coded, but was incomplete.  
i have finished this code and seems to be working properly now.
main is updated with this fix.

**Comment by ryllae** [comment]
Easy way to still create a phantom slot: unfit a module in space.

**Comment by zhyrohaad** [comment]
lol
nice.
will look into that one

**Comment by zhyrohaad** [comment]
the "inspace" bit is still problematic.
remove works, and shows a free slot, however, trying to autofit doesnt work, as seen here.
also the error msg is a bit wonky.
![2019 09 14 04 45 30](https://user-images.githubusercontent.com/6365054/64903540-a1c96880-d680-11e9-89fe-199911d5bce4.png)

dragging module to specific slot gives error also.
![2019 09 14 04 46 45](https://user-images.githubusercontent.com/6365054/64903550-d2a99d80-d680-11e9-8deb-ad35f0b37e81.png)

am digging into this more.

**Comment by zhyrohaad** [comment]
found some bad logic and duplicate calls in this method.
working on a fix

**Comment by ryllae** [comment]
This is still possible in an Orca.  Open the fitting window in space, remove some low slots, can you can't replace the slots (phantom object again).   Strip fitting crashes the server.

**Comment by zhyrohaad** [comment]
yeah, there are still errors with modules.
have not fixed/updated anything with them yet.
this is current focus.

**Comment by zhyrohaad** [comment]
found fitting error.
testing fix

**Comment by zhyrohaad** [comment]
main updated

**Comment by ryllae** [comment]
I've only been able to get a phantom slot once so far, I can't reproduce it consistently yet, and it doesn't crash, so I'm going to call this good.  Although there are still unfitting issues to be debugged: https://github.com/zhyrohaad/AlasiyaEvE/issues/77

**Comment by zhyrohaad** [comment]
i got 2 on separate occasions, but both were without trying and couldnt reproduce at all.
i think it may have something to deal with internal client timers and the fact i was stepping thru code (so responses to client were delayed)
because of that, and i coudnt reproduce on demand, i called it fixed.
