### ISSUE TITLE
asteroid distances are wrong for operating strip miners

### ISSUE THREAD

**Issue by tercenya** [zhyrohaad/AlasiyaEvE#2]
**Describe the bug**
A strip miner thinks an asteroid is further away than the overview says it is.

**To Reproduce**
go to `G-Q5JU`, equip a Hulk with an Ore Strip Miners.  Fly within 15K of an asteroid, and activate the strip miner.  It will say the asteroid is 20+km away.  Might be related to some diameter calculations?

**Comment by THUNDERGROOVE** [comment]
This is very likely to be a client desync.  You can quickly check if this is the case with the .syncloc command.

There's still work to be done on destiny to keep the client and server positions in sync.  The whole system client side uses SSE2 instructions for optimization so it's not the easiest stuff to reverse engineer.

It is on my TODO list to pull some data sets from the client and write up a mock destiny system for quick iteration to ensure we get the math _right_

**Comment by zhyrohaad** [comment]
it's also not just that one solar system.  it's the same for all.
seems like i broke mining while fixing something else.

**Comment by ryllae** [comment]
Apparently a better distance calculation is to measure from the asteroid's diameter (not the center of mass). 

This should also fix survey scanners.

**Comment by ryllae** [comment]
This is also more apparent in deep space where asteroids are 10-15km in size.

**Comment by zhyrohaad** [comment]
seems to be working fine now, but i havnt tried losec/nullsec yet.
this fix has been pushed to main server.
please test again to verify

**Comment by ryllae** [comment]
Skill broken.  it's easy to test in nullsec due to the huge rocks:
![Capture4](https://user-images.githubusercontent.com/51723245/63242745-00d0c480-c21e-11e9-9523-811ccaebc9d5.PNG)

**Comment by ryllae** [comment]
A quick bit of math shows that the server thinks I'm 27647m away, but the client thinks I'm ~18km.  That's a difference of 9647 ≈ 9583, which is exactly the radius of the asteroid.

**Comment by ryllae** [comment]
My survey scanner, which has a range of 22.5km, is also empty.  it should have 4 items.

**Comment by zhyrohaad** [comment]
i'll have to test in nullsec and see what needs to be done.
i have also updated roid sizes, so that may help also.

**Comment by zhyrohaad** [comment]
the survey scanner returning no results, which is a different bug, is now fixed and working correctly.

**Comment by ryllae** [comment]
I get results, they're just affected by the bug, that's all:
![Capture14](https://user-images.githubusercontent.com/51723245/63661894-eba9e780-c781-11e9-9cad-47a5526c72fd.PNG)

**Comment by zhyrohaad** [comment]
oh!!   i see what you're talking about now.
yeah, i'll update this next chance i get.

**Comment by zhyrohaad** [comment]
fixed and updated main server
pls test again to verify

**Comment by zhyrohaad** [comment]
@tercenya please test this and close issue if fix acceptable

**Comment by ryllae** [comment]
Looks good to me!
