### ISSUE TITLE
Engineering skills don't apply to ships while flying in space

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#20]
Train Engineering 5.  Take a Hawk ( which only has 45MW powergrid by default), but now you have 56.3, which is enough to fit a 10MN AB.  Fit it, and you trigger this bug (https://github.com/zhyrohaad/AlasiyaEvE/issues/10), but it's still fit and online.    Undock.  You'll trigger the same error message again, except that if you click "fitting", you'll see you don't actually have 56.3 powergrid anymore, you're back to 45, and there is no way to online the AB (even if https://github.com/zhyrohaad/AlasiyaEvE/issues/14 were fixed).

**Comment by zhyrohaad** [comment]
i'll look over skill fx and see what needs to be done.
i'll post when its updated

**Comment by zhyrohaad** [comment]
it turns out that many effects were not being applied properly due to an update of the number handling system.
this has been fixed but is part of a larger fix, so main is not updated yet.
i will post again when i update main

**Comment by zhyrohaad** [comment]
number handling system is corrected and working properly again.

this fixed a number of bugs,

main is updated, so test again when you get time.

**Comment by ryllae** [comment]
Look good so far.
