### ISSUE TITLE
Logging out does not save your current position

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#21]
Logging out in space or another station always returns you to your starting station upon next login.  Your last position is not being saved.

**Comment by zhyrohaad** [comment]
this is very odd.
i'll see whats going on and post with my findings

**Comment by zhyrohaad** [comment]
this is some weird shit here.
character locations are NOT being updated, and ive no clue why.
the calls are going thru.  the data is right.  somehow its not updating the db as it should.
i'll keep poking around.

**Comment by zhyrohaad** [comment]
found and fixed the error.
it was part of an 'update' where i missed a char variable.
am still testing other fixes and will post when i update main

**Comment by zhyrohaad** [comment]
there is (was) also a problem with another save call that mangled ship positioning on save.
this has also been corrected and updated.

**Comment by ryllae** [comment]
Deja vu fixed.  Maybe we're not living in the matrix after all.
