### ISSUE TITLE
new .tr no longer accepts the most basic use case

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#22]
While I like the new extra features of `.tr`, it no longer handles the most basic case:  `.tr Rens` gives an error "Translocate: Missing Arguments"

**Comment by THUNDERGROOVE** [comment]
I believe you can get around this by doing `.tr me Rens` but I haven't
tested it yet.

**Comment by ryllae** [comment]
`.tr me Rens` -> "translocate: invalid location 0"

**Comment by zhyrohaad** [comment]
i dont remember if string search is implemented in this version.
ill have to look.

**Comment by zhyrohaad** [comment]
it wasnt, but it is now
`.tr` now accepts system and station names, and will work on both of the following:
`.tr Rens`
`.tr me Rens`

**Comment by ryllae** [comment]
Yea!  that's so much better than looking up `.tr 30002510` and fat-fingering the number...

**Comment by zhyrohaad** [comment]
also note that there is only limited checks for locationIDs as numbers.
if you enter an invalid location, it may or may not be caught (and probably not at this point) and will break your character on your next login.
just be aware of this when entering locationIDs
