### ISSUE TITLE
Hulk is OP when fitted with *8* strip miners

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#23]
![Capture](https://user-images.githubusercontent.com/51723245/63567310-9d54d880-c536-11e9-86f7-133f40841b78.PNG)

Alas, I can't online all of them until https://github.com/zhyrohaad/AlasiyaEvE/issues/20 is fixes, but who's counting?

Fit a Hulk with 3 strip miners, then logout. Log back in and all 3 will be offline, and phantomed. Equip 5 more in slots that don't exist.

If you remove one first, you can sometimes get the new miners to even show up on the fitting screen, at the risk of only being able to equip 7 🤷‍♂

**Comment by zhyrohaad** [comment]
whoa.
wtf is going on there?????
ok, so im gonna have to try to reproduce that one.
wasnt sure it was possible, but wow......
thats some wild shit there.
good find!

**Comment by zhyrohaad** [comment]
i tried this one, but wasnt able to reproduce it.
i have managed to find and fix multiple other module code errors.
main has been updated, so test again and report findings, pls.

**Comment by ryllae** [comment]
I no longer have extra slots.  There are ways to equipment multiple items in the same slot, but that bug isn't exactly this one, and it appears to have no adverse effects at the moment besides making your fitting window stupid.  I'll call this fixed.
