### ISSUE TITLE
Can't fit 3 turrets on a Rifter

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#24]
No shenanigans or phantom slots involved here:  just buy a rifter, and try to fit 3x Republic Fleet 200mm AC.  You get stuck after 2:
![Capture2](https://user-images.githubusercontent.com/51723245/63570520-2bcf5700-c543-11e9-95cf-966bc7d7c369.PNG)

If you unequip them, you can't fit any!

**Comment by zhyrohaad** [comment]
i am updating these checks along with other fixes.
i believe the counting is a lil off on these, from my own recent testing.

**Comment by zhyrohaad** [comment]
this seems to be fixed, from my testing.
main has been updated.

**Comment by ryllae** [comment]
There are only two hard bugs in programming: naming, cache invalidation, and off-by-one errors.

**Comment by zhyrohaad** [comment]
LOL  good one.  and so true!
i would have gone so far to say
"there are only 10 hard bugs......"
but that also plays into "there are only 10 kinds of people.....those that understand binary and those that dont."
