### ISSUE TITLE
Can't load new zones by jumping or .tr

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#26]
Often after jumping through a gate, my Overview is empty, my ship doesn't appear, and the zone won't load.  `.bubbleinfo` shows that other players are near me at the gate after the transition.  If you right click in space, I see all the objects, but I don't have a "Warp To" options.  Sometimes my overview is accurate, but I can't interact with any items there.  This also happens after using `.tr`. 

This does *not* happen after undocking.  Logging off and back on appears to cure the current zone.

**Comment by ryllae** [comment]
We've seen this bug before, not sure why it's back now.

**Comment by zhyrohaad** [comment]
this is a new one.
i have found the problem, but not sure why its happening
the system state isnt being updated properly....
while is shows you in the 'new' system, and the system id in top left is correct, the overview is data from previous system.
im not sure why this is happening, but its borked on dev server also.
am working to correct this now.

notice the difference between location info in top left and information on overview.  (previous system was yuzier)
![2019 08 25 04 50 35](https://user-images.githubusercontent.com/6365054/63645708-0de02e80-c6ca-11e9-85ac-a6e9741955cb.png)

**Comment by ryllae** [comment]
Confirmed, that's the (broken) behavior that I see.

**Comment by zhyrohaad** [comment]
fixed and updated

**Comment by ryllae** [comment]
`.tr` often requires an `.update` after changing systems, but since that's not core functionality, I'll close this.  Until `.tr` breaks again.
