### ISSUE TITLE
activating a Shield Transporter reports a range of 0

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#27]
Equip a X-Large S95a Shield Transporter, target a nearby ship (range: 200m), activate, then see an error message complaining that 0 < the suggested 8400m range:
![Capture16](https://user-images.githubusercontent.com/51723245/63739200-0d729f80-c852-11e9-9ac0-e1ec082dc7ca.PNG)

**Comment by zhyrohaad** [comment]
oh wow.
guess i havent tested those yet.
i'll have to see what's going on there.
will post when i have something to report.

**Comment by zhyrohaad** [comment]
this is using same code as the problem in issue #2, but there is a bit of data missing.
the check code is right now, but i have found there are multiple range types that we arent checking/setting yet.
i will post when i have it updated.

**Comment by zhyrohaad** [comment]
data found and fixed
main server updated

pls test again to verify problem is fixed

**Comment by zhyrohaad** [comment]
revisited this code earlier and found a few things that werent being properly set or checked.
i have rewrote the distance checking code to use the correct attributes for the module activated.
previous 'fix' was just a hack by manipulating data, but this time i was able to find the proper attributes and implement correct checks.

again, pls verify

**Comment by ryllae** [comment]
Much better!  Also tested Remote cap transfer, seems to work correctly.
