### ISSUE TITLE
Overfilling your cargo gives a bogus error message

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#29]
Drag an *excessive* volume of items to your cargohold, and you get an improperly formatted error message.  This appears often when moving multiple stacks of multiple items:
![Capture20](https://user-images.githubusercontent.com/51723245/63740646-845e6700-c857-11e9-8971-877cd2e27fde.PNG)

**Comment by zhyrohaad** [comment]
i have noticed this, but cannot consistently reproduce, which makes it hard to track.
i do have it on the list to look into, when i find it.

this msg is one of the multitude "preprogrammed" client error msgs i have recently (within past year) implemented, and have not fully tested.

**Comment by zhyrohaad** [comment]
fixed and main is updated
pls test to verify

**Comment by ryllae** [comment]
Still a bug.  Best way to reproduce: 
In an Orca, add metric ton of Veldspar to your Cargo Hold (this may violate your actual space).
Drag the entire stack to the 1nd Division tab.

You can also do this easily between division tabs.

If you first try to drag to the OreHold first, you can encounter https://github.com/zhyrohaad/AlasiyaEvE/issues/37, creating smaller stacks, then subsequently move SOME of the ore before hitting this bug?  Reason is not clear.

There are also ways to trigger this without the Division tabs and just use the orehold and cargo hold, but it takes more setup.

**Comment by zhyrohaad** [comment]
single stacks work as intended (deliberate error on jetcan capy)
![2019 09 02 06 24 33](https://user-images.githubusercontent.com/6365054/64094217-a73dbf00-cd20-11e9-9bee-dcb2eed30a35.png)
![2019 09 02 06 24 41](https://user-images.githubusercontent.com/6365054/64094225-ae64cd00-cd20-11e9-927d-d66e3a563fcc.png)
![2019 09 02 06 24 57](https://user-images.githubusercontent.com/6365054/64094237-b45aae00-cd20-11e9-849e-c49799c64e59.png)

**Comment by zhyrohaad** [comment]
nm.  found it.
took a bit of playing, but found and working on a fix.
also looking into why the capy checks arent working for corp hangars and other containers.
will post when fixed and updated.

**Comment by zhyrohaad** [comment]
found errors and missing checks/data for inventory tests.
this has been rewritten and corrected.
main is now running this updated code.

**Comment by ryllae** [comment]
Found other bugs, but not this one.  Assuming we're good here.
