### ISSUE TITLE
OnItemChange exception client side preventing inventory updates

### ISSUE THREAD

**Issue by THUNDERGROOVE** [zhyrohaad/AlasiyaEvE#3]
**Describe the bug**
When an item is added to an inventory during gameplay two exceptions are thrown client side

`227	2019.06.02 17:49:22:143	EXCEPTION #24 logged at  06/02/2019 10:49:23
228	2019.06.02 17:49:22:143	Caught at:
229	2019.06.02 17:49:22:143	/common/lib/bluepy.py(86) CallWrapper
230	2019.06.02 17:49:22:143	/common/script/sys/servicemanager.py(670) MollycoddledUthread
231	2019.06.02 17:49:22:143	Thrown at:
232	2019.06.02 17:49:22:143	/common/script/sys/servicemanager.py(667) MollycoddledUthread
233	2019.06.02 17:49:22:143	/client/script/ui/services/skillsvc.py(139) OnItemChange
234	2019.06.02 17:49:22:143	item = 90000056
235	2019.06.02 17:49:22:143	self = <svc.SkillsSvc instance at 0x4A365918>
236	2019.06.02 17:49:22:143	change = {3: 0}
237	2019.06.02 17:49:22:143	AttributeError: 'int' object has no attribute 'categoryID'
`

`243	2019.06.02 17:49:22:144	EXCEPTION #25 logged at  06/02/2019 10:49:23
244	2019.06.02 17:49:22:144	Caught at:
245	2019.06.02 17:49:22:144	/common/lib/bluepy.py(86) CallWrapper
246	2019.06.02 17:49:22:144	/common/script/sys/servicemanager.py(670) MollycoddledUthread
247	2019.06.02 17:49:22:144	Thrown at:
248	2019.06.02 17:49:22:144	/common/script/sys/servicemanager.py(667) MollycoddledUthread
249	2019.06.02 17:49:22:144	/client/script/environment/invcache.py(245) OnItemChange
250	2019.06.02 17:49:22:144	item = 60014137
251	2019.06.02 17:49:22:144	self = <svc.invCache instance at 0x07279E18>
252	2019.06.02 17:49:22:144	change = {3: 0}
253	2019.06.02 17:49:22:144	UnboundLocalError: local variable 'lockKey' referenced before assignment
`

**To Reproduce**
.create or buy item from the market

**Expected behavior**
Item will be shown in your hanger.

**Comment by zhyrohaad** [comment]
i cannot reproduce this bug on dev server
may be db problem on main, but unknown at this time.

**Comment by zhyrohaad** [comment]
after playing around with changing items, i was able to occasionally duplicate this error.
still not sure why it's being thrown, and seems quite elusive (to me on dev server)
will continue working on this one.

**Comment by zhyrohaad** [comment]
found a couple things that COULD be the problem,so i rewrote them and cant duplicate error.
this fix has been pushed to main server.
please test again to verify

**Comment by ryllae** [comment]
Tested and working: assembling ships, moving items between ship's cargo and station hanger, repackaging ships

**Comment by zhyrohaad** [comment]
@THUNDERGROOVE needs to verify this so we can close it, pls.

**Comment by THUNDERGROOVE** [comment]
Will check tomorrow and close it.

**Comment by THUNDERGROOVE** [comment]
Fixed!
