### ISSUE TITLE
Orca: Using fitting services in space breaks your slots

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#33]
Undock an Orca, remove a cargo expander (works). Try to remove another cargo expander, get an error about stacking assembled items.  Try to put it back, get an error that there's already something in that (now empty) slot.  Docking up doesn't fix this problem.

Similar to: https://github.com/zhyrohaad/AlasiyaEvE/issues/19

**Comment by ryllae** [comment]
![Capture25](https://user-images.githubusercontent.com/51723245/63741588-5549f480-c85b-11e9-83a3-ff847f4ded17.PNG)

**Comment by zhyrohaad** [comment]
this is odd.
i dont think it's specific to orca, or to ships in general
i think this may be part of the "moving items between containers" problems, which are working for most things.
ill look into this again.

**Comment by ryllae** [comment]
Correct, this is just how all fitting in space works right now.  This is just another instance of Phantom slots (as confirmed by the StripFit Crash Check).  Closing in favor of https://github.com/zhyrohaad/AlasiyaEvE/issues/19 which has this same info.

There's obviously a second bug about the "stacking assembled items" to look into as well.
