### ISSUE TITLE
Insurance: minor UI bug

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#34]
An insured ship doesn't properly show the label for the level of insurance when inspected.
![Capture26](https://user-images.githubusercontent.com/51723245/63742175-94794500-c85d-11e9-94cf-9a227b8aad6d.PNG)

**Comment by zhyrohaad** [comment]
oh, right.....that damn minimum coverage.
i changed it from live, and didnt even think about client data.
i'll put that on the list for later.

**Comment by zhyrohaad** [comment]
this has been updated.
test again to verify, pls

**Comment by ryllae** [comment]
No change in the UI: an uninsured ship shows a red "Uninsured" as expected, but a ship with insurance still looks as above.  However, I can no longer insure ships to test this further: https://github.com/zhyrohaad/AlasiyaEvE/issues/50

**Comment by zhyrohaad** [comment]
updated.

**Comment by zhyrohaad** [comment]
any update on this bug?

**Comment by ryllae** [comment]
Looks good.
