### ISSUE TITLE
Freighters data are mismatched

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#35]
My Charon has 3 low slots (that didn't appear until the [Kronos expansion](https://www.eveonline.com/article/patch-notes-for-kronos) but I have all the bonus stats (like the 785k m^3 base volume and 4+AU/s warp speed) from Crucible.

This allows for an obscene >2 *million* m^3 cargo charon fit:
![Capture30](https://user-images.githubusercontent.com/51723245/63743170-01daa500-c861-11e9-8004-38f8f34fc95c.PNG)

**Comment by ryllae** [comment]
Freighters also have the -100% bulkhead CPU reduction: https://github.com/zhyrohaad/AlasiyaEvE/issues/36  but we don't have the rest of the items that came with Kronos that can be fit there, such as the (non-rig) Hyperspatial Accelerators, Jump Fuel Conservation Modules, etc..

**Comment by zhyrohaad** [comment]
so, the easiest fix for this, and #36 would be to remove the low slots?
i'll look into that as i get time.  maybe soon to resolve these 2 bugs.

**Comment by ryllae** [comment]
Removing the low slots would a workaround to #36, because the client isn't totally accepting of this this mishmash.  Some metadata (such as cargohold size and warp speed, fitting numbers) from Crucible, but things like slots and the bonus dogma are from later xpacs.  

I know the issues are related, but my goal in this issue was to highlight that the mismatched data, and that you can do some rather egregious things because of it.  Having a freighter with too much cargohold isn't really that terrible.  Confusing the hell out of the UI and fitting tool because the data are broken - rather problematic.  If you can fix the data as discussed over in #36, both of these problems would be fixed.  If you want to massage the data to avoid #36, I'll probably just go looking for more nonsense, because Freighters are surely not the only thing that was changed...

**Comment by zhyrohaad** [comment]
point taken.
however, i just grabbed the first set of fx data that had all the info i needed.
i didnt look to see what all was changed.
this will be a project i'd rather delegate, as i dont have much time, and this will consume a lot of it.

any volunteers?

**Comment by zhyrohaad** [comment]
found my notes and data where i was working on fx.
testing old data with new system and will update main when im satisfied with tests.

**Comment by zhyrohaad** [comment]
fixed and updated

**Comment by ryllae** [comment]
My existing freighter still has phantom low slots (as a result of items already in low slots that no longer exist), but spawning a new freighter looks correct to me.  Though I do miss the Kronos quality of life improvements...
