### ISSUE TITLE
evel knievel: you can board a ship a high speed and it keeps going (then position desyncs)

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#39]
You only allow ejections from ships at full stop, but you can Board Ship at full speed (provided you pass within 500m).   You may want to disallow Boarding at high speed for the same reasons.

Also, your old ship starts to decelerate, but it's final resting spot on the server isn't anywhere close to where the client says it should be.  An unmanned ship should decelerate faster: https://github.com/zhyrohaad/AlasiyaEvE/issues/38

**Comment by zhyrohaad** [comment]
well, thats' something i havent thought about.
i bet that's a bitch to time, tho.   how many tries did it take?

ships decel at same rate no matter what.  it's part of eve physics.
this will be disabled till i can do something with it.

**Comment by ryllae** [comment]
It's not too hard, because the target ship can't be moving.  Just click "Approach", and soon as you're within 500m, click Board?

**Comment by zhyrohaad** [comment]
yeah, i just updated....i have checks for TARGET ship moving, not pilot's ship.
so, until some later time when this is revisited, this will be disabled.

**Comment by zhyrohaad** [comment]
see updates in #38

**Comment by ryllae** [comment]
That's definitely a a quality of life improvement.  I've seen one spurious error message so far, but can't reproduce it yet.  I'll call this good.
