### ISSUE TITLE
Rorqual Maintenance Bay not limited to mining barges

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#41]
yeah, I know, caps aren't implemented, but this is an item movement restriction!  Will also be a bug when https://github.com/zhyrohaad/AlasiyaEvE/issues/31 gets fixed.

**Comment by zhyrohaad** [comment]
actually, that check should work.
all the checks for moving items from one point to another are coded.
i'll put it on the list.

**Comment by zhyrohaad** [comment]
ive tested this and havent found a problem with it.

**Comment by zhyrohaad** [comment]
for some reason, i cant upload ss, so here's links

https://pasteboard.co/Ivi6vR7.png
https://pasteboard.co/Ivi6X4E.png
https://pasteboard.co/Ivi7yHl.png

**Comment by ryllae** [comment]
see https://pasteboard.co/Ivi6vR7.png: 
![Capture46](https://user-images.githubusercontent.com/51723245/64071460-358e4400-cc40-11e9-8db9-cc9bed0f221c.PNG)

There's a Minmatar shuttle in your maintenance bay.  That's not a mining barge:
![Capture47](https://user-images.githubusercontent.com/51723245/64071466-4f2f8b80-cc40-11e9-97e4-ced07385c0ca.PNG)

**Comment by ryllae** [comment]
Technically it's not *just* barges:  Indy ships such at an Iteron or maybe even a Noctis should also be valid.

But the fact that I can put a Rokh or a Hawk in there is wrong.

**Comment by zhyrohaad** [comment]
ahhhh
wasnt aware of that restriction, nor have i looked for it.
will rewrite checks and update as i get time.

**Comment by zhyrohaad** [comment]
just noticed i even have the error msg stating "....ship's *INDUSTRIAL* ship hold...."  
italics and bold added for emphasis.
fixing checks now, along with other item movement errors/omissions.

**Comment by zhyrohaad** [comment]
main has been updated with this fix.
also note, there were multiple other inventory checks that were unfinished/missing and added to this update.
because the cleint will send a particular cargo hold flag in it's request, the server is ONLY checking what the client sends, and not what it should be.
because of this, some ships MAY have wrong hold flag set, so the server will allow things that apparently dont belong, but actually do.

**Comment by ryllae** [comment]
Tested with numerous ships.  Occator, check, Hulk, Check.  Orca... almost fits (too bad).  Noctis, yes. 
 Primae, yes.  Zephyr.. yes (interesting).  Combat ships, nope.  Shuttles, nope

Looks good.
