### ISSUE TITLE
Founded a corporation, starts with two members and a segfault

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#42]
Elathine Calandiel is the founding member of a seminal corporation:

It reports having two members, but I'm the only one there.
![Capture41](https://user-images.githubusercontent.com/51723245/63822285-8129b080-c915-11e9-8b3f-d4ddd5932c38.PNG)
![Capture42](https://user-images.githubusercontent.com/51723245/63822290-85ee6480-c915-11e9-86d3-469d530a5285.PNG)

I closed the window, attempted to buy an Office (which failed due to lack of corp funds, will need to embezzle some), so I reopened the corp window.  And the server immediately crashed.

Attempting to login with this toon now also crashes the server.

Long live _*NULL_

**Comment by zhyrohaad** [comment]
sweet
that sounds like a ticker check i'll have to implement.

here is a link to corp shit working.
however, i only tried doing things that you're "supposed" to do.....
havent tried anything unexpected.....like a null ticker.  ;)

http://eve.alasiya.net/gallery/Corporations/

**Comment by ryllae** [comment]
I just created a second Corp, and it started with 2 members.  Clicking on the members tab immediately crashes the server:
![Capture45](https://user-images.githubusercontent.com/51723245/63901616-edb2b700-c9ca-11e9-8315-bb0ad422e80d.PNG)

**Comment by zhyrohaad** [comment]
actually, the `*NULL` ticker seems to be ok.   i see no reason to disallow it.
i have also fixed the member count and login segfault (which was actually an assert)

try again and post results.

**Comment by ryllae** [comment]
I can log in, and the member tab works!  but the Member Count on the first page still reports 2, even though there is only one member.

**Comment by zhyrohaad** [comment]
oh, right.
i didnt change it in db after i made fix.
doing that now.

**Comment by zhyrohaad** [comment]
any update on this?

**Comment by ryllae** [comment]
I didn't create any new corps, but the current count looks right, so I'm assuming all is good.
