### ISSUE TITLE
Disco Fever: Smartbombs are duds?

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#44]
Equiped a YF-12A Smartbomb on a Hawk.  Undocked, and activated it with ships nearby.  Nothing happened.  No VFX either?

**Comment by zhyrohaad** [comment]
nope.
these arent coded at all....not even skeleton code.  (well, this one may have skeleton code)
they are part of the handful of modules i havent touched yet, for various reasons.
at this time, it's not very high on the list (and hasnt been).

**Comment by zhyrohaad** [comment]
At this time, and for the foreseeable future, this will be listed as "Won't fix".
It may be revisited at a later date.
