### ISSUE TITLE
Corporation Details Window doesn't list Offices

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#46]
Start a corporation, give it some money.  Rent an Office at the local space station.  Open the Corporation Window -> Home -> Details.  "Your corporation has no offices"

![Capture48](https://user-images.githubusercontent.com/51723245/64071968-cd455f80-cc4b-11e9-8994-f73ead91f6a9.PNG)

**Comment by zhyrohaad** [comment]
damn.
this was working at one time.
ive no clue yet, but will add it to the list.

**Comment by zhyrohaad** [comment]
just tested on dev server.  
![2019 09 14 04 13 30](https://user-images.githubusercontent.com/6365054/64903338-39788800-d67c-11e9-8c48-58b37e071246.png)

will test on main after i update to verify

**Comment by ryllae** [comment]
Looks good.
