### ISSUE TITLE
Mining has a NULL target

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#5]
**Describe the bug**
Attempting to mine results in a "You can't attack (NULL)"

**To Reproduce**
Tested point-blank in multiple locations.  Not likely related to https://github.com/zhyrohaad/AlasiyaEvE/issues/2

**Comment by zhyrohaad** [comment]
this was fully functional at one time.
is a high priority issue now

**Comment by zhyrohaad** [comment]
all active modules run thru a series of checks before activation.
this particular check uses the "isOffensive" attribute, which is supposed to check activation of weapons against non-combatant targets.
with the check failing at this point, and i cant reproduce this error on dev server,  im led to believe there is an attribute data error in main server. 
as there seems to be multiple other attribute checks that arent working right, this seems to be resulting from possible incomplete data in main server's db.

however the "(NULL)" in the msg bothers me.   i dont know what that's from, or why the target's name would be "(NULL)".

**Comment by zhyrohaad** [comment]
found it and fixed.  
very elusive error on dev server, as there are more layers of checks that main didnt have.
this fix has been pushed to main server.
please test again to verify

**Comment by ryllae** [comment]
All better now.  Tested with Strip Miners
