### ISSUE TITLE
Can no longer insure ships

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#50]
Try to insure a ship at any level.  Get an error message complaining that you're not paying enough?  I was previously able to insure ships.

![Capture51](https://user-images.githubusercontent.com/51723245/64072058-0e3e7380-cc4e-11e9-9ae1-b478f1c896ad.PNG)

**Comment by zhyrohaad** [comment]
wonderful.
by removing that 0.3 it has caused a number of problems with insurance.
i'll have to revisit it and see what i can do.

**Comment by zhyrohaad** [comment]
updated

**Comment by ryllae** [comment]
Still broken.  Can't insure my Caracal at any level.

**Comment by zhyrohaad** [comment]
working on dev.
![2019 09 14 04 15 42](https://user-images.githubusercontent.com/6365054/64903352-6dec4400-d67c-11e9-90de-33c7239a80a1.png)

will test main after next update

**Comment by ryllae** [comment]
Working again as intended.  Except for the few things that aren't.  Will open separate bugs in a moment.
