### ISSUE TITLE
Depleting Asteroid causes segfault when mining cycle ends

### ISSUE THREAD

**Issue by zhyrohaad** [zhyrohaad/AlasiyaEvE#52]
**Describe the bug**
*see title*

**To Reproduce**
mine all available ore from asteroid

**Expected behavior**
ore moved into hold, mining laser stops after cycle completes

**Comment by zhyrohaad** [comment]
(treating this as any other bug report, i am commenting as i would any other)
this system hasnt been discussed much, and since we've lost the post about it on forums, i'll dive a bit deeper here.   (i'll recreate the forum post eventually)
target manager does just that......manages targets.
this system is simple, but the code gets complicated.
it deals with all possible actions dealing with items being targetted, and even tracks what modules on which ships are active on a given target.
all SystemEntities (any item in space) have a targetMgr.
when an SE is destroyed, a call is made to all ships targetting this item, as well as all modules currently active on this item.
there are multiple calls to targetMgr that have to be in order, mostly because the system hasnt been optimized yet to self-call all needed methods to complete the task it should be doing.
this particular call was missing when asteroids were depleted.

it is fixed now.
currently undergoing testing.

**Comment by ryllae** [comment]
Can also report that Salvaging causes a segfault upon success.

**Comment by zhyrohaad** [comment]
found few other errors with mining while debugging this segfault.
currently working on dev server.  
polishing and gonna push to main for more testing

salvage error should be separate issue.

**Comment by zhyrohaad** [comment]
main updated.
will test when time permits

**Comment by ryllae** [comment]
Still crashes with strip miners.

**Comment by zhyrohaad** [comment]
ok.  i'll dig into it when i can.

**Comment by zhyrohaad** [comment]
working.
main updated with fix
