### ISSUE TITLE
A repackaged ship keeps its insurance

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#54]
Insure a ship at any level.  Repackage it, then reassemble it.  Reopen the insurance window.  It's still insured.

Expected: Repackaging a ship should remove insurance.

Not tested: trading a ship that's already insured.

**Comment by zhyrohaad** [comment]
havent thought of this one.
should be an easy fix.

i can tell you right now that trading will do same thing.
there are no checks for that anywhere, except for insuring a ship already insured.

**Comment by zhyrohaad** [comment]
wrote checks for this.
will push to main with other updates later.
** UPDATE **
fix pushed to main.

**Comment by ryllae** [comment]
Works.

**Comment by ryllae** [comment]
Though if you have the insurance window when you hit repackage, it doesn't update.   Not sure if that's expected on this client or not.
