### ISSUE TITLE
Attacking another player causes a segfault

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#55]
I undocked two toons in 1.0 space directly off of Amsen VI-1.  From my Rokh, I target the Noctis.  I clicked the Nova Heavy Missile in the Missile Launcher, get a notice that this would be a rather unfortunate act in high sec.  Accept, YOLO.  The missile fires, appears to land on the target, and the server immediately crashes.  

Expected: I get CONCORDoken.  And the server doesn't crash 💣

**Comment by zhyrohaad** [comment]
should be no different than firing missiles at npcs.
will look into this.

ps...there is no concord yet.

**Comment by zhyrohaad** [comment]
is this different than firing at NPCs?
meaning, does server crash when missile hits npc also, or just player?

**Comment by ryllae** [comment]
Was PC only, NPCs were working fine.  But it appears to be fixed.
