### ISSUE TITLE
Tractor Beam Tug of War

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#56]
Setup: Take a pair of Noctis equipped with tractor beams, and a wreck inbetween.  ship 1 tries the pull the wreck towards them.  Ship 2 counters with one of of his own.  The wreck with approach ship 2.  disable all Tractor beams on ship 2, and the wreck doesn't move.

Expected: It seems like the last person to engage their beam always wins, but disabling your tractor beams doesn't  allow someone else to win?  Also, I'm not sure you're actually supposed to be able to have multiple targets tractoring at once?

![Capture54](https://user-images.githubusercontent.com/51723245/65365451-00419a00-dbdf-11e9-9c46-6d25bf1f3102.PNG)

**Comment by zhyrohaad** [comment]
havent thought of this one
will look into it....should be an easy fix

**Comment by zhyrohaad** [comment]
updated.
test again when ya get time, pls.

**Comment by zhyrohaad** [comment]
any updates on this?

**Comment by ryllae** [comment]
Still exists:  Target a wreck, and activate two tractor beams on it.  Disable the 2nd one, and the wreck stops moving.  (You probably shouldn't be able to target it twice).  Tug of war between two ships always has the last tractor beam winning, even if it gets disabled.

**Comment by zhyrohaad** [comment]
will look over this again.

** update **
this falls into #70 with target/module shit.
will work on it with other module fixes

**Comment by zhyrohaad** [comment]
have added checks for multiple tractors on same object.
have also added code to check ownership (which may be bypassed later)
also again added code per discussion on tractorable items which is currently disabled.

to document here, that discussion boiled down to all player-type objects are able to be tractored, not just cargo cans and wrecks, with the exception of anything anchored (which is the point of anchoring) or under player control (like piloted ships and linked drones).
there will be limitations on sizes and speeds, with larger things needing cap tractors (like pos modules or large ships)

**Comment by zhyrohaad** [comment]
main updated

**Comment by ryllae** [comment]
I get a "no messageId 259628", but no longer can have two tractor beams on one target

**Comment by zhyrohaad** [comment]
i'll make a note.
kinda weird, tho....those messageId #s are pulled from client.
it's THEIR shit, so why is it undefined????

i'd call this one fixed and close it.
the invalid msg# is neither here nor there.  (and will correct it later)

**Comment by ryllae** [comment]
Close enough for government work.
