### ISSUE TITLE
Taking a spacewalk creates the Picard Maneuver, causes players to appear in two places at once

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#6]
**Describe the bug**
When ejecting from a ship, you are marked as still commanding the previous vessel, as well as your pod.  This also means that noone (including you) can get back into your ship.  Also of note, your pod appears to be limited to 1m/s, but `.location` disagrees.  If you `.kill` the "abandoned" vessel, both the ship and your pod explode, also disproving established rules of [Quantum Mechanics](https://en.wikipedia.org/wiki/Quantum_superposition).

**To Reproduce**
Undock, Eject from ship.  Attempt to reboard the "already occupied" vessel.  _Show info_ displays you piloting both ships.

**Comment by zhyrohaad** [comment]
there is a problem with the ships pilot (your char) not being updated correctly on eject.
this shows the ship is still being piloted, and also explains why you get podded when ship is killed.
working on this fix now.

**Comment by zhyrohaad** [comment]
seems to be fixed.
this has been pushed to main server.
please test again to verify

**Comment by ryllae** [comment]
All better now.
