### ISSUE TITLE
Launching a control tower causes a segfault

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#60]
acquire a control tower of choice, fly it out to a vacant moon, click "launch for corporation".  <crash>

This fails in both high and null sec space.

**Comment by zhyrohaad** [comment]
another error i saw in console.
was db query error.
fixed so try again and lemme know.

**Comment by ryllae** [comment]
Tested in Period Basis.  Still crashes on 'Launch for Corp'

**Comment by zhyrohaad** [comment]
the "launch" code needs to be gone over again, now that some other systems are maturing.
however, any "launch for corp" calls are still incomplete.....there are still some corp items incomplete also.
this work will resume at a later date (tba)

**Comment by zhyrohaad** [comment]
launch code has been revised.
testing and looking over some other pos items before updating main.

**Comment by zhyrohaad** [comment]
main updated.
as a side note, scooping POS items will reset their data.  
please scoop pos items then re-deploy before continuing testing.

**Comment by ryllae** [comment]
I can successfully launch and online a POS
