### ISSUE TITLE
Segfault: Inserting fuel in a control tower fuel bay

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#65]
Launch a control tower (challenging until https://github.com/zhyrohaad/AlasiyaEvE/issues/60 is resolved).  Anchor it, wait 30 minutes.  Start the online process.  Insert 20,000 fuel blocks in the fuel bay.  :bomb:

**Comment by zhyrohaad** [comment]
there are many POS systems incomplete at this time.
this work will resume at a later date (tba)

**Comment by zhyrohaad** [comment]
looking into this problem.
easy to reproduce.
so far, hard to track.
will update when i have something worth posting.

**Comment by zhyrohaad** [comment]
found and fixed.
main updated
pls test again to verify

**Comment by ryllae** [comment]
Looks good, besides https://github.com/zhyrohaad/AlasiyaEvE/issues/68
