### ISSUE TITLE
Can no longer lock more than one target at a time

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#69]
Try to lock two targets.  Receive a message saying you can't lock more than one targets (sp).  Tested in an Orca and Caracel, on characters that have at least one point trained in Multitasking.

**Comment by ryllae** [comment]
might have been borked when https://github.com/zhyrohaad/AlasiyaEvE/issues/59 was fixed?

**Comment by zhyrohaad** [comment]
i've noticed this on myself.
completely different code segment from #59 

** update **
think i found it....testing

** update again **
found.  
i had a ">" where i should have had a "<".
will update main when i push multiple other updates (couple days or so)

**Comment by zhyrohaad** [comment]
main updated

**Comment by ryllae** [comment]
Much better.
