### ISSUE TITLE
Missiles continue to shoot after target is unlocked

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#70]
Lock a player target, start firing a Heavy Missile Launcher.  Unlock the target.  The launcher continues to fire.

Expected: Unlocked targets should disable weapons that were tracking them

**Comment by zhyrohaad** [comment]
hmmm
have to say here's another i hadnt thought of trying

its' not just missiles.
its all modules that affect a target...turns out there is no code to update module manager the target has been unlocked, except on destruction.

**Comment by zhyrohaad** [comment]
found, fixed and updated main server.

** update **
nope....still broke.
trying to find out why

**Comment by zhyrohaad** [comment]
this should be fixed on latest update

**Comment by ryllae** [comment]
Tested with my RNI, looks better.
