### ISSUE TITLE
Salvage Success causes segfault

### ISSUE THREAD

**Issue by zhyrohaad** [zhyrohaad/AlasiyaEvE#71]
**Describe the bug**
see title

**To Reproduce**
salvage a wreck and wait for success

**Expected behavior**
salvage wrecks without crashing server

**Comment by zhyrohaad** [comment]
this error has been found and am currently testing a fix

while tracing this, also found salvage items dont scale with wreck size.
this will be fixed also.

**Comment by ryllae** [comment]
also noted here: https://github.com/zhyrohaad/AlasiyaEvE/issues/52

**Comment by zhyrohaad** [comment]
salvage items scale was being reset before use (stupid re-init) and is fixed.
segfault was from wreck being deleted multiple times.
or it could have been trying to deref the wreckSE after being deleted the first time.
either way, it's fixed now.
