### ISSUE TITLE
Autoreload fails, and breaks in many ways

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#73]
Fit a Heavy Missile Launcher II, load it with missiles, commence firing.  When the launcher runs out, the UI shows "1" missile remaining, but you can no longer disable the module, or have access to any of the the right-click menu (eg, to force a reload).  The launcher cycles forever, and no auto-reload happens.  You cannot drag additional missiles to the launcher to change or reload the missiles.

**Comment by ryllae** [comment]
ps I think this is a regression, I thought weapon autoreload was working in the past?

**Comment by zhyrohaad** [comment]
welcome to my world.  :(

** edit for my notes **
any module that uses charges has this problem.
once last charge is used, code kinda gets confused, so AM::Proc() checks are wrong for this scenario.
AM::Proc() !reload and state < deactivating.
module button shows cycling and single charge left.
cannot stop, offline module continues cycle.  can reload with no effect.
removing module resets cycle timer and will then function normally till charge is out again.
need to walk thru and verify process logic.

**Comment by zhyrohaad** [comment]
charge code and relevant data updated.
this should be fixed now, as well as a few other problems with load, unload and module charge counts.

on a tech side, module states and checks were refined and updated, which enables better module control,.  
this update allowed the incorrect charge data to be more prominent, which was working thru a nasty hack previously that i wasnt aware of.
this has been corrected to proper data handing and main server updated.

**Comment by zhyrohaad** [comment]
code wasnt finished.  
didnt realize it till tonite.
have now finished code, tested, optimized and am quite happy with results.
this also fixes phantom charges when removing/unloading modules and charges.

**Comment by ryllae** [comment]
Testing notes from my Raven Navy Issue.  I put my 8x Dread Guristas Heavy Missile Launchers into an Action Group.  Reloaded with Nova Heavy Missiles, started PEWPEW.  When they ran out, it didn't autoreload, and the module appeared to continue to cycle.  I was able to right click and reload them manually.   Now the missle loaded count no longer decreased as I kept shooting.  After running out again. clicking the launcher said I was out of missiles, but I couldn't reload manually.

**Comment by zhyrohaad** [comment]
hmm
will have to look into it more.
i used AC in my test.  will try missiles next

**Comment by zhyrohaad** [comment]
module charge code fixed by minor rewrite.
all charges now behave properly, and havent been able to reproduce the phantom slots again.
main updated

**Comment by ryllae** [comment]
My latest test of autoreload caused a crash.  But there were other people online causing crashes, so I will need to test this again at a quiet time to double check.

**Comment by zhyrohaad** [comment]
The charge code is mostly separate from other module updates, so shouldn't be affected by other errors found.  
However, based on past history, this is probably broken differently now.  😉

**Comment by ryllae** [comment]
I was able to duplicate several behaviors with the above missile launchers, enough to get you going:  When I let a missile launcher run out of missiles on its own, it stays activated and spins forever with one (phantom?) charge.   If you disable the missile launcher as it hits one charge left, then restart the launcher, you see visually go empty, but upon attempting reload, segfault.  

I haven't quite tested restarting the stuck missile launcher or doing a manual reload on a stuck launcher, as it's probably in an invalid state already.

**Comment by zhyrohaad** [comment]
As a side note, docking resets all skills, ship, modules and effects
***edit***
yes, the 'stuck launcher' is in an invalid state at that point, and code tests will report "Your xxx doesnt appear to be loaded..."
this is part of the 'invCache is processing an ixQuantity change" errors.
i am currerntly working on fixing this one.

2Mar20
as a side note, i have fixed the ixQuantity error.
charge counts are accurate in their respective module until first reload...whether it's from empty magazine or manual ammo change, at which point the behavior noted above happens.

current workaround is dock, wait for session change to complete, undock.

this is current priority.

**Comment by zhyrohaad** [comment]
this rework has been completed and my testing shows it working properly

**Comment by ryllae** [comment]
Autoreload works, though it stops firing on the target.  That may be working as intended?

**Comment by zhyrohaad** [comment]
yes, there is no autofire after reload.
i have looked into implementing that, and can without too many problems, but live doesnt with good reason, and i agree with it.
therefore, this is working as intended.
