### ISSUE TITLE
segfault: Click on "EVE Mail"

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#79]
^^

The window appears to open on the client, so I'm assuming it's one of the mail enumeration calls?

**Comment by zhyrohaad** [comment]
@THUNDERGROOVE did mail.
blame him.
:p

**Comment by ryllae** [comment]
[proof is the pudding](https://www.git-scm.com/docs/git-blame)

**Comment by zhyrohaad** [comment]
this doesnt crash
there's nothing there (unless you send mail), but i cant get it to crash.

more info, plz.

**Comment by ryllae** [comment]
Still crashes the instant that the Mail UI pops.. and then every subsequent login until I reset my cache (so the window stays closed on login).  You should see several segfaults around this timestamp.

Since I can't open the mailbox, I don't know if it's because there's mail there or something there causing the issue.  Sorry for the scant info, LMK next time you're online and I'll make some more crashes for you to look at.

**Comment by zhyrohaad** [comment]
i get home around 6am CST so anytime around there is fine.
i ususally get to bed around 730am CST, so crash around 6-630 will give me time to look at it.
i;ll look into putting my dev server hooked to outside again too.   makes it a bit easier to track and whatnot

**Comment by zhyrohaad** [comment]
found it.
bad db calls when data populated.
i couldnt find errors on dev because i dont have mail...easy to test with an empty set.
segfault fixed, but mail system still incomplete

**Comment by ryllae** [comment]
> fixed, mail system still incomplete

That's fine.  Was just honked that everytime I accidentally clicked on mail, I crashed then I couldn't login again until I deleted the toon cache because it would try to open the mail window again on login and just crash some more...
