### ISSUE TITLE
When undocking, you cannot see any nearby ships

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#8]
**Describe the bug**
When undocking, people in space already can see you, but [you can't see them](https://www.youtube.com/watch?v=C-M2hs3sXGo&t=8).

**To Reproduce**
Undock Toon X. Undock Toon Y.  Undock Toon Z.   X can see Y and Z.  Y can see Z.  Z sees noone.  A local scan by Z shows there are nearby ships, but they aren't in overview.   If Z warps away and comes back, she can see X and Y now.

**Comment by zhyrohaad** [comment]
wow.
nice destiny/sysMgr error there.
did you happen to notice the chat when this was happening?
im thinking it follows the same pattern, meaning existing players can see new arrivals, but new arrivals cannot see existing.

**Comment by zhyrohaad** [comment]
cannot reproduce this bug on dev server.
tried with 3 clients.
various combinations of each dock/undock/warpin/warpout with no problems
also, there are cli commands for bubble/destiny bug tracking that i wrote for inventory tracking, which may be relevant here
for bubble tracking use ".bubblelist" for your current bubble
destiny variables are shown in ".destinyvars"
your current container's inventory can be viewed using ".inventory"
your ship inventory can be viewed with ".shipinventory"
and there are a few others i cant think of offhand.

**Comment by zhyrohaad** [comment]
working dev code (that i couldnt reproduce this error on) has been pushed to main server.
please test again to verify the fix

**Comment by ryllae** [comment]
This appears to be fine, but I'm going to wait to close it until we can warp/dock without abusing `.tr`

**Comment by zhyrohaad** [comment]
ship movement seems to be fixed.
pls test again and report back with findings

**Comment by ryllae** [comment]
Just undocked several toons, looks right.
