### ISSUE TITLE
Ships that join a bubble aren't notified of decelerations in progress

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#80]
**Describe the bug**
Given a ship (A) joins a bubble (via undock or warp) and a ship (B) that is already in the bubble who are decelerating (via the Stop The Ship) A never receives notice that B is slowing down.  On B's screen, A continues to steam ahead at the velocity that A saw B when it joined the bubble, as where on B's screen, B slows and [eventually] reaches a stop.

**To Reproduce**
Undock a Nyx.  As soon as you reach space, hit Stop The Ship.  Immediately undock a Buzzard. Note the current speed of the Nyx when the Buzzard appears on field.  On the Buzzard's screen, the Nyx will continue to move away at ~65m/s, while on the Nyx's screen, she reaches a stop (usually ontop of the Buzzard!)

**Additional context**
Using `.syncloc` on the Nyx causes the Nyx to reappear ontop of the Buzzard's screen briefly, but the buzzard still thinks the Nyx has speed.  `.update` *on the Buzzard* forces B to notice the correct speed speed and location of the Nyx (while usually removing the Buzzard's speedometer https://github.com/zhyrohaad/AlasiyaEvE/issues/40).

**Comment by ryllae** [comment]
This also explains some of the behavior of https://github.com/zhyrohaad/AlasiyaEvE/issues/39 and issues while testing https://github.com/zhyrohaad/AlasiyaEvE/issues/38

**Comment by zhyrohaad** [comment]
this is a destiny state problem
i will have to do some digging to find out why.
this may also be tied into why ships warping into a bubble appear to enter bubble outer edge at a full stop, then accelerate/decel to final warp position.

**Comment by zhyrohaad** [comment]
as to the other movement errors, it may be relevant.
i'll have to do some digging and testing to figure it out.

**Comment by zhyrohaad** [comment]
found, fixed, updated

**Comment by ryllae** [comment]
Looks good.
