### ISSUE TITLE
Dragging a mod between slots gives an error; fails.

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#83]
While docked, open fitting, equip an Afterburner in a midslot.  Drag it to the neighboring slot, crash the server.  Also tested with a highslot (salvager).

**Comment by zhyrohaad** [comment]
I had just spent hours testing all combos I could come up with and no problems.
Will get on this my earliest chance.

**Comment by zhyrohaad** [comment]
found and fixed.
it was code i added last-minute AFTER testing, and didnt test it.
turns out, was trying to dereference a null pointer without checking first.
easy fix.  ;)

**Comment by ryllae** [comment]
Well, we're not crashing, but now I'm seeing an error dialog: `These locations are not compatible`

**Comment by zhyrohaad** [comment]
OMG.
Simple check, but I've managed to screw it up.  Lol.  Will fix soon

**Comment by zhyrohaad** [comment]
fixed and updated
