### ISSUE TITLE
Cannot Mine

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#85]
Equip a Hulk with Strip Miners, target some Veldspar.  I get an error: `You cannot attack the Veldspar.  Serverref error: 16228`

**Comment by zhyrohaad** [comment]
Not that again.  🤔

**UPDATE**
It was "that" again.
This is one of db code error symptoms mentioned in the market error bug.
It has been fixed.

**Comment by ryllae** [comment]
The spice must flow.
