### ISSUE TITLE
Jettisoning multiple items at once attempts to create multiple jetcans

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#88]
Select multiple items in your cargo hold.  Right click, Jettison.  You get an error stating that you need another 600 seconds to prep a new jetcan.  Only the first item was moved to the created jetcan. 

Expected: All selected items should be jettisoned at once?

**Comment by zhyrohaad** [comment]
Yes, of this I am aware. 
 Jetcans still busted.

**Comment by zhyrohaad** [comment]
simple coding error (isnt that a surprise?)
testing fix

***update***
this has been fixed.
main not updated yet

**Comment by ryllae** [comment]
confirmed fixed
