### ISSUE TITLE
Skills and ship/item description are not working

### ISSUE THREAD

**Issue by steinrock** [zhyrohaad/AlasiyaEvE#9]
https://www.youtube.com/watch?v=SA7_D3tYAQE first 3 minutes

**Comment by zhyrohaad** [comment]
this was fully functional at one time.
is a high priority issue now

**Comment by zhyrohaad** [comment]
this fix has been pushed to main server.
please test again to verify

**Comment by zhyrohaad** [comment]
@steinrock pls test to verify fix and close if acceptable

**Comment by zhyrohaad** [comment]
no update from issue reporter
all descriptions are working for me.
closing this issue as resolved
