### ISSUE TITLE
Character with no training queue shows that it will finish in the distant past

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#98]
My toon has no training queue, but the login screen shows that her queue will finish around when King George IV was crowned...

Also, shouldn't this be an duration not a date?

![Annotation 2020-02-19 133731](https://user-images.githubusercontent.com/51723245/74869545-c4da0180-531d-11ea-84db-ad86791513d7.png)

**Comment by zhyrohaad** [comment]
Whoa.  When did that start???
Again, this too was working for last 5-6 years.
Either way, will find out soon.

**Comment by zhyrohaad** [comment]
Turns out there is some weird things going on with skill training again.  
Not sure whats going on yet

**Comment by ryllae** [comment]
Since I crashed the server more than a few times tonight, had a chance to pass by the login screen many times, figured I'd investigate this.  On one toon, I had a skill queued that I already trained.  removing it and hitting apply fixed the issue.

My other toon legitimately had no queue, but also said it would finish training in 1921.  Hitting "Pause" on skill training asked me if I really wanted to do that (why, it's empty?), then hitting apply seems to have cleared whatever the DB thought I wasn't training?

As I recall, EVE in this era had a *robust* cronjob that cleaned a lot of crap up.  You might consider one at some point to clean up "data disparities" and such that won't go away on their own.

**Comment by zhyrohaad** [comment]
the problem with running cron on that is i dont know what constitutes a data disparity until i get a note about it....like this one.   but the downside of this is using a proc tic to load, parse, then verify all possible skill training problems.
i do know when the queue is being processed correctly, everythings fine.
there is a processing error (on client side) with training a skill to L5 in the queue, which is causing problems.
this error is one of those problems.
on login, char skills ARE parsed for level and SP errors, but time is not.
i think the easiest thing would be to add the skill time to the other skill checks.
i do plan on looking over the completion time display on char select screen and see what i can do for it.
i have a feeling it will self-correct when the training queue errors are fixed.

**Comment by zhyrohaad** [comment]
added another (redundant) check for skill training.
this seems to have fixed the L5 problem, which will self-correct the time issue

**Comment by ryllae** [comment]
I haven't been able to reproduce this consistently of late, will reopen if I find something useful later.

**Comment by zhyrohaad** [comment]
to test it, i was setting the "finish time" in the db between a minute and couple hours before my login time.
there may be a hiccup still there, but i didnt find any this round.
